### ISSUE TITLE
4/27欠席します

### ISSUE THREAD

**Issue by sueki743** [UTokyo-SDP/git-ex-02-group-23#2]
4/27(金)の授業は申し訳ないのですが欠席します！よろしくお願いします！

**Comment by minori5214** [comment]
了解です！
連絡ありがとうございます！

**Comment by minori5214** [comment]
お疲れ様です。
今日はExcercise2でしたが、課題1番が終わらないまま終わってしまいました。
課題1番はやるので、もし時間があれば課題2番（PUT）を担当して頂けると助かります。
（必ずしも３つともやらなくてはならないわけではないらしいのと、次回の5/8の授業中くらいまでに終われば大丈夫みたいなので、連休中に無理にやらなくても全く問題ないと思います。）
宜しくお願いします！

**Comment by sueki743** [comment]
了解です！
